baseURL: https://waterwaycleanups.org/
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
    parser:
      attribute:
        block: true

params:
  stripe_publishable_key: "pk_live_51S5BvA3dx9K6lxUY472msOL3O84VqAq3Q2ZrYJ3Zy4GQaOpaxvZvHEjU1ImpzkktgwGf7z4Qcsy9jQ1dSBldHujH00vQMi7OOx"

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
    permalinks:
      page:
        posts: /blog/:slug
        services: /services/:slug
        products: /webshop/:slug
        events: /events/:slug
        projects: /projects/:slug
        merchandise: /merchandise/:slug
      section:
        posts: /blog/
        services: /services/
        products: /webshop/
        events: /events/
        projects: /projects/
        merchandise: /merchandise/
