on:
  workflow_dispatch:
jobs:
  create-date-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate next date-based release tag
        id: generate_release_tag
        uses: "amitsingh-007/next-release-tag@v6.3.0" #
        with:
          tag_prefix: "deploy/*"
          tag_template: "yyyy.mm.dd.i" # Example format: 2026.01.09.1
          github_token: ${{ secrets.GITHUB_TOKEN }}
